version: '3.1'
services:
  nginx:
    image: 'nginx:1.17.9'
    restart: always
    container_name: jiang-nginx
    ports:
      - 9002:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./wwwroot:/usr/share/nginx/wwwroot